shared:
    image: node:6

jobs:
    main:
        steps:
            - install: npm install
            - test: npm test
        requires:
            - ~pr
            - ~commit

    publish:
        steps:
            - install: npm install --no-save semantic-release@^7
            - publish: npm run semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Github token to push tags to Git
            - GH_TOKEN
        requires:
            - main
